development:
  adapter: postgresql
  encoding: unicode
  database: rcop_development
  pool: 5

test:
  adapter: postgresql
  database: rcop_test
  encoding: unicode

production:
  adapter: postgresql
  encoding: unicode
  database: rcop_production
  pool: 3

